### ISSUE TITLE
Adding New Tabs and Widgets and Actually Running the Final Project

### ISSUE THREAD

**Issue by BriannaSmithR** [cssearcy/AYS-R-Coding-SPR-2020#26]
I'm not even sure what the directions mean, so that's my starting point. 
When you say add new tabs to the dashboard, I'm assuming you mean add two new drop down menus similar to the ones we already have in the script like those for which direction the car is going in and what day it is, etc. Are we just adding those so that they're actually functional or making those functional as well as adding at least two more tabs? I used the following code to try to add another input, but it's not working! It says I have unused arguments. I just wanted to make one that showed whether there was harm or not. 
```
sliderInput(inputID = "harm",
            label = h3("Accident Including Harm or Not"),
            choices = c("Harm", "No Harm"))
```
Is a widget just like the output that you get? Like the map we made in Lab 4 was a widget or am I totally off?

My last issue is that I don't understand how to make it run. When I was doing the other shiny lab, I had two tabs and could run one of them I think? Now, I have the two docs that you provided, but I genuinely don't know what the difference is or how to run either of them to see what works.

I'm about to watch the youtube video you made on this project, so maybe that'll answer some of my questions. I just wanted to get them out there so I could start actually figuring this stuff out.

**Comment by jamisoncrawford** [comment]
@BriannaSmithR did you figure this out then?

**Comment by BriannaSmithR** [comment]
"Figured out" is a strong term. I remembered that your youtube videos exist, so I'm going through that now and hoping.
