### ISSUE TITLE
Lab 2 Q 7

### ISSUE THREAD

**Issue by marissafallico** [cssearcy/AYS-R-Coding-SPR-2020#36]
Hello! I'm confused on question 7 part 2. I'm unsure how to subset the proper dollars and return a numerical value as opposed to a count. This is affecting my ability to complete the challenge questions as well. Thanks!

**Comment by jamisoncrawford** [comment]
Hi @marissafallico, I believe this was answered in #34 

Please see that and let us know if it helps.

**Comment by jamisoncrawford** [comment]
@marissafallico is this resolved?

**Comment by marissafallico** [comment]
Hi! I went through the entire question board and stared at that particular answer for about an hour before posting and still seem to be having issues figuring out how to format the code. I can keep playing around with it.

**Comment by marissafallico** [comment]
Managed to figure it out. Thanks!

**Comment by jamisoncrawford** [comment]
@marissafallico awesome, sure thing and thanks for letting us know!
